[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true
stderr_logfile=/var/log/php-fpm.err.log
stdout_logfile=/var/log/php-fpm.out.log

[program:websocket]
command=php /var/www/html/websocket/server.php
autostart=true
autorestart=true
stderr_logfile=/var/log/websocket.err.log
stdout_logfile=/var/log/websocket.out.log

[program:monitor]
command=php /var/www/html/artisan monitor:screens
autostart=true
autorestart=true
startsecs=0
startretries=9999
stderr_logfile=/var/log/monitor.err.log
stdout_logfile=/var/log/monitor.out.log
