-- ── IPTV Menu Appearance Columns ───────────────────────────────
-- ستون‌های ظاهری منو: پس‌زمینه، لوگو، خوش‌آمد، accent، ticker
-- سازگار با MySQL 8 (ADD COLUMN IF NOT EXISTS فقط MariaDB)

SET @db = DATABASE();

SET @q = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='iptv_menus' AND COLUMN_NAME='bg_image')=0,'ALTER TABLE iptv_menus ADD COLUMN bg_image VARCHAR(500) DEFAULT NULL','SELECT 1');
PREPARE s FROM @q; EXECUTE s; DEALLOCATE PREPARE s;

SET @q = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='iptv_menus' AND COLUMN_NAME='logo_url')=0,'ALTER TABLE iptv_menus ADD COLUMN logo_url VARCHAR(500) DEFAULT NULL','SELECT 1');
PREPARE s FROM @q; EXECUTE s; DEALLOCATE PREPARE s;

SET @q = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='iptv_menus' AND COLUMN_NAME='welcome_title')=0,'ALTER TABLE iptv_menus ADD COLUMN welcome_title VARCHAR(200) DEFAULT NULL','SELECT 1');
PREPARE s FROM @q; EXECUTE s; DEALLOCATE PREPARE s;

SET @q = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='iptv_menus' AND COLUMN_NAME='welcome_sub')=0,'ALTER TABLE iptv_menus ADD COLUMN welcome_sub VARCHAR(300) DEFAULT NULL','SELECT 1');
PREPARE s FROM @q; EXECUTE s; DEALLOCATE PREPARE s;

SET @q = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='iptv_menus' AND COLUMN_NAME='accent_color')=0,'ALTER TABLE iptv_menus ADD COLUMN accent_color VARCHAR(7) NOT NULL DEFAULT \'#ef4444\'','SELECT 1');
PREPARE s FROM @q; EXECUTE s; DEALLOCATE PREPARE s;

SET @q = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='iptv_menus' AND COLUMN_NAME='bg_dim')=0,'ALTER TABLE iptv_menus ADD COLUMN bg_dim DECIMAL(3,2) NOT NULL DEFAULT 0.55','SELECT 1');
PREPARE s FROM @q; EXECUTE s; DEALLOCATE PREPARE s;

SET @q = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='iptv_menus' AND COLUMN_NAME='bg_blur')=0,'ALTER TABLE iptv_menus ADD COLUMN bg_blur TINYINT UNSIGNED NOT NULL DEFAULT 0','SELECT 1');
PREPARE s FROM @q; EXECUTE s; DEALLOCATE PREPARE s;

SET @q = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='iptv_menus' AND COLUMN_NAME='ticker_text')=0,'ALTER TABLE iptv_menus ADD COLUMN ticker_text TEXT DEFAULT NULL','SELECT 1');
PREPARE s FROM @q; EXECUTE s; DEALLOCATE PREPARE s;

SET @q = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='iptv_menus' AND COLUMN_NAME='ticker_color')=0,'ALTER TABLE iptv_menus ADD COLUMN ticker_color VARCHAR(7) NOT NULL DEFAULT \'#ffffff\'','SELECT 1');
PREPARE s FROM @q; EXECUTE s; DEALLOCATE PREPARE s;

SET @q = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='iptv_menus' AND COLUMN_NAME='ticker_bg')=0,'ALTER TABLE iptv_menus ADD COLUMN ticker_bg VARCHAR(7) NOT NULL DEFAULT \'#000000\'','SELECT 1');
PREPARE s FROM @q; EXECUTE s; DEALLOCATE PREPARE s;

SET @q = IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='iptv_menus' AND COLUMN_NAME='ticker_speed')=0,'ALTER TABLE iptv_menus ADD COLUMN ticker_speed TINYINT UNSIGNED NOT NULL DEFAULT 40','SELECT 1');
PREPARE s FROM @q; EXECUTE s; DEALLOCATE PREPARE s;
